name: Deploy on self-hosted
on:
  push:
    branches: [ "main" ]  # 메인 브랜치 푸시에 자동 배포

jobs:
  deploy:
    runs-on: self-hosted  # 해당 러너 라벨 확인 필요
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 서브모듈(wsie-back)까지 필요하면 주석 해제
          # submodules: true

      - name: Show versions (optional)
        run: |
          docker version
          docker compose version

      - name: Compose up (build & run)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          # 이미지가 있으면 최신으로, 없어도 무시
          docker compose pull || true
          docker compose up -d --build

      - name: Check containers (optional)
        run: |
          docker ps
          docker compose logs --no-color --tail=200

